apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:16
          ports:
            - containerPort: 1433
          env:
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postressecret
                key: PG_PASSWORD
          volumeMounts:
          - mountPath: /var/lib/postgresql/data
            name: postgres-pv-storage
      volumes:
      - name: postgresdb
        PersistentVolumeClaim:
          claimName: postgres-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
  - name: postgresql
    protocol: TCP
    port: 1433
    targetPort: 1433
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: postgresql
  ports:
  - protocol: TCP
    port: 1433
    targetPort: 1433